name: Deploy ERP

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: self-hosted

    steps:

      - name: Update Repository
        run: |
          cd /opt/k3s-lab/apps/erp-django/erp-django
          git pull origin main

      - name: Build Image
        run: |
          cd /opt/k3s-lab/apps/erp-django/erp-django/app
          sudo docker build -t erp-django:latest .

      - name: Import Image
        run: |
          cd /opt/k3s-lab/apps/erp-django/erp-django/app
          sudo docker save erp-django:latest -o erp.tar
          sudo k3s ctr images import erp.tar

      - name: Restart Deployment
        run: |
          kubectl rollout restart deployment/erp-django -n erp

      - name: Wait Rollout
        run: |
          kubectl rollout status deployment/erp-django -n erp
